language: php

sudo: false

env:
    - COMPOSER_ARGS=''

matrix:
  include:
    - php: 7.1
      env:
          - COMPOSER_ARGS='--prefer-stable'
    - php: 7.1
      env:
          - COMPOSER_ARGS='--prefer-lowest'
    - php: 7.2
    - php: 7.3
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer update -n "$COMPOSER_ARGS"

script:
    - vendor/bin/phpunit
